import { Providers } from "../providers";
import { Inter } from "next/font/google";
import "../globals.css";
import TopNavBar from "@/components/shared/TopNavBar";
import ShoppingCart from "@/components/shared/ShoppingCart";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main>
          <Providers>
            <TopNavBar />
            {/* <ShoppingCart /> */}
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
