import Header from "@/components/server/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import StoreProvider from "./reduxToolkit/StoreProvider";
import { ApiProvider } from "@reduxjs/toolkit/dist/query/react";
import Provider from "./reduxToolkit/services/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@2.51.6/dist/full.css"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css"
          rel="stylesheet"
          type="text/css"
        />
      </head>

      <body>
        <StoreProvider>
          {/* <Provider> */}
          <Header />
          {children}
          {/* </Provider> */}
        </StoreProvider>
      </body>
    </html>
  );
}
