import { Inter } from "next/font/google";
import { Providers } from "../providers";
import "../globals.css";
import { redirect } from "next/navigation";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // * Fetch Mongo-user and check if its role is admin or not?

  // fetchUser(); ...

  // * if not! redirect to home

  redirect("/");
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
